version: '3.9'

services:
  pgdb:
    container_name: pgdb_fastapi
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - ./.env
    environment:
#      - ./.env
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pgdb
    volumes:
      - pgdb:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  pgdb:
